name: docker-image-push-to-dockerhub-CI

on:
  push:
    branches:
      - main #Trigger on push to 'main'
      - dev
  pull_request:
    branches:
      - main #Trigger on pull request to 'main'
      - dev
jobs:
  build-and-push:
    runs-on: ubuntu-latest #Use latest Ubuntu

    steps:
      - name: 1. Checkout code #code clone
        uses: actions/checkout@v3

      - name: 2. Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21' #Java version 21
          distribution: 'temurin' #Temurin distribution

      - name: 3. Build with Maven
        run: mvn clean install #Maven Build

      - name: 4. Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 5. Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}} #Retrived from GitHub Secrets
          password: ${{secrets.DOCKER_PASSWORD}} #Retrived from GitHub Secrets

      - name: 6. Build and Push Docker Image #Pushing Docker image into DockerHub
        uses: docker/build-push-action@v5
        with:
          context: . #Current location
          file: ./Dockerfile #Docker file path
          push: true #Push Image
          #tags: ${{secrets.DOCKER_USERNAME}}/student-appcd:latest #tag
          tags: ${{secrets.DOCKER_USERNAME}}/employeeappci:${{github.sha}} #tag




